# fly.toml app configuration file generated for sendnotes-long-wind-1214 on 2024-06-25T15:39:23-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sendnotes-long-wind-1214'
primary_region = 'ewr'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '18'
    PHP_VERSION = '8.3'

[env]
  APP_ENV = 'production'
  DB_CONNECTION = 'pgsql'
  APP_URL = 'https://sendnotes-long-wind-1214.fly.dev'
  MAIL_MAILER = 'postmark'
  MAIL_FROM_ADDRESS = 'sendnotes@gregorypaulrothstein.dev'
  MAIL_FROM_NAME = 'The Sendnotes App'
  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'info'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
  SESSION_DRIVER = 'cookie'
  SESSION_SECURE_COOKIE = 'true'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[deploy]
  release_command = 'php /var/www/html/artisan migrate --force'

[processes]
  app = ""
  cron = "cron -f"
  worker = "php artisan queue:listen"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
